version: '3'

services:
  webhook:
    build: .
    command: npx nodemon index.js --watch src
    ports:
      - 3030:3030
    volumes:
      - .:/alice
      - node_modules_volume:/alice/node_modules

  ngrok:
    image: wernight/ngrok
    command: ngrok http --region=eu webhook:3030
    ports:
      - 4040:4040

volumes:
  node_modules_volume:
